### ISSUE TITLE
Issue with amf-json-ld-lib@0.0.13 with using node version ^14.15.4

### ISSUE THREAD

**Issue by LokeshNSF** [advanced-rest-client/amf-helper-mixin#43]
We are using node version 14.15.4 and with the introduction of the new dependency amf-json-ld-lib@0.0.13, our build is failing with error - "The engine "node" is incompatible with this module. Expected version ^12.16.0. Got 14.15.4"

This issue seems to have been fixed in the amf-json-ld-lib version - 0.0.14. It would be great if this library is updated in the code.

Can you please help in resolving this issue ASAP.

Thanks

**Comment by jarrodek** [comment]
@TwoPlusTwoOne can you take a look into this?

**Comment by LokeshNSF** [comment]
@TwoPlusTwoOne Any updates on this issue?

Thanks.

**Comment by TwoPlusTwoOne** [comment]
Hi @LokeshNSF , I will be updating in the next release which will be coming out Monday at the latest

**Comment by LokeshNSF** [comment]
Thanks for the update @TwoPlusTwoOne.
